name: notes_and_more
description: Info- und Todo-Manager

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase: ^7.0.0
  firebase_auth:
  firebase_auth_web:
  firebase_database: ^3.0.7
  autocomplete_textfield: ^1.7.3
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/flutter-icon.png
